// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: snippets.sql

package db

import (
	"context"
	"time"
)

const createSnippet = `-- name: CreateSnippet :one
INSERT INTO snippets (
    title,
    content,
    expires
) VALUES (
    $1, $2, $3
) RETURNING id, title, content, created, expires
`

type CreateSnippetParams struct {
	Title   string    `json:"title"`
	Content string    `json:"content"`
	Expires time.Time `json:"expires"`
}

func (q *Queries) CreateSnippet(ctx context.Context, arg CreateSnippetParams) (Snippet, error) {
	row := q.db.QueryRowContext(ctx, createSnippet, arg.Title, arg.Content, arg.Expires)
	var i Snippet
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Created,
		&i.Expires,
	)
	return i, err
}
